/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_FILENAME NONE|DISABLE.
*/

#ifndef _foundation_import_h__
#define _foundation_import_h__

# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

# import <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

#endif
