/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _foundation_include_h__
#define _foundation_include_h__

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-objc-compat/mulle-objc-compat.h>   // mulle-objc-compat

// library: remove with `mark no-header`, rename with `set include`
# include <objc-compat/objc-compat.h>   // objc-compat

#endif
