/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _foundation_import_h__
#define _foundation_import_h__

# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

#endif
