/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _foundation_include_private_h__
#define _foundation_include_private_h__

/* no headers */

#endif
